export const LIDERES = Object.freeze([
  'Amairany Yepez Gómez',
  'Camilo Velasquez Restrepo',
  'Johan Stivens Carmona Giraldo',
  'Juan Jose Martinez Velasquez',
  'Juliana Quiroz Upegui',
  'July Andrea Cardenas Montaño',
  'Karen Johanna Reyes Rivera',
  'Leon Dario Arango Amaya',
  'Maria Isabel Gomez Londoño',
  'Saúl Naranjo Romero',
  'Sebastian Cuervo Aransazo',
  'Veronica Espinosa Artunduaga',
  'Victoria Eugenia Loaiza Pérez',
  'Yilmer Moreno Salas',
]);

export const CARGOS = Object.freeze([
  'Analista de Soporte',
  'Analista Funcional e commerce',
  'Aprendiz de Desarrollo de Software',
  'Aprendiz de Diseño Gráfico',
  'Arquitecto de Datos',
  'Auxiliar Contable',
  'CEO',
  'Científico de Datos',
  'Country Manager México',
  'Country Manager Spain',
  'Culture & People Specialist',
  'Custumer Surces',
  'Data Analyst',
  'Data Engineer',
  'Delivery Manager',
  'Digital Marketing Specialist',
  'Director de Producto',
  'Director of Experience',
  'Diseñadora Gráfica Publicitaria',
  'Engineering Director',
  'Financial & Administrative Director',
  'Functional Specialist',
  'Operations Director',
  'Practicante de Desarrollo de Software',
  'Presales & Functional Specialist',
  'QA Analyst',
  'Sale Developmen Representative',
  'Scrum Master Delivery Manager',
  'Software Developer',
  'UX | UI Creative',
  'UX | UI Creative Chapter Lead',
]);

export const AREAS = Object.freeze([
  'Tecnología / TI',
  'Operaciones',
  'Gestión Humana / RRHH',
  'Administración',
  'Finanzas / Contabilidad',
  'Comercial / Ventas',
  'Marketing',
  'Diseño / UX',
  'Soporte Técnico',
  'Calidad / QA',
  'Analítica de Datos',
  'Legal / Auditoría',
]);

export const CLIENTES = Object.freeze([
  'EXPERIMENTALITY',
  'SURA',
  'SOLLA',
  'EXITO',
  'GRUPO NUTRESA',
  'SURAMERICANA',
  'BANCO DE BOGOTÁ',
  'ALKOSTO',
  'OTRO',
]);

export const APLICACIONES = Object.freeze([
  'GITHUB', 'GITLAB', 'BITBUCKET',
  'AWS', 'GCP', 'AZURE',
  'SLACK', 'MICROSOFT TEAMS', 'ZOOM', 'DISCORD',
  'GOOGLE WORKSPACE', 'MICROSOFT 365',
  'JIRA', 'CONFLUENCE', 'NOTION', 'CLICKUP', 'TRELLO', 'AZURE DEVOPS',
  'FIGMA',
  'HUBSPOT', 'SALESFORCE',
  'VTEX', 'SHOPIFY',
  'BUK', 'TALANA', 'BAMBOOHR',
  'SIESA', 'QUICKBOOKS',
  '1PASSWORD', 'BITWARDEN', 'LASTPASS',
  'JENKINS', 'SONARQUBE', 'DATADOG', 'NEW RELIC',
  'OTRO',
]);

export const ROLES = Object.freeze([
  'Administrador',
  'Desarrollador / Developer',
  'Visualizador / Lector',
  'Analista de QA / Tester',
  'Editor / Creador de contenido',
  'Soporte / Service Desk',
  'Project Manager / Scrum Master',
  'OTRO',
]);
